const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3010'
const DEMO_MODE = import.meta.env.DEV || import.meta.env.VITE_DEMO_MODE === 'true'

export interface Patient { id: string; first_name: string; last_name: string; phone?: string; email?: string; gender?: string; date_of_birth?: string; notes?: string; last_visit?: string | null; next_appointment?: string | null }
export interface Appointment { id: string; patient_id: string; appointment_date: string; appointment_time: string; duration: number; appointment_type: string; status: string; reason: string; notes: string; first_name: string; last_name: string; phone: string; email?: string; gender: string }
export interface DentistNote { id: string; title: string; content: string; expires_at: string; is_active: boolean; created_by?: string | null; created_at: string; updated_at: string }
export interface DentistNoteInput { title: string; content: string; expiresAt?: string | null }
export interface InventoryItem { id: string; name: string; category: string; quantity: number; reorder_level: number; unit: string; is_active?: boolean; low_stock?: boolean }
export interface InventoryInput { name: string; category: string; quantity: number; reorderLevel: number; unit: string }
export interface SupportMessage { id: string; conversation_id: string; sender_id: string; sender_name?: string | null; sender_role: string; body: string; created_at: string }
export interface SupportConversation { id: string; subject: string; status: 'open' | 'closed'; created_by?: string | null; created_at: string; updated_at: string }
export interface SupportChat { conversation: SupportConversation | null; messages: SupportMessage[] }
export interface HospitalDirectory { id: string; name: string; relationship: 'own' | 'partner'; specialty: string; address: string; city: string; contact_name?: string; contact_phone?: string; is_active?: boolean }
export interface NotificationAlert { id: string; kind: 'message' | 'email' | 'call'; title: string; body: string; customer_name?: string | null; is_read: boolean; created_at: string }
export interface ClinicSettings { clinic_name: string; clinic_email?: string; phone?: string; address: Record<string, unknown>; branding: Record<string, string>; working_hours: Record<string, string>; appointment_settings: Record<string, unknown>; notifications: Record<string, boolean>; timezone: string }
export interface DashboardData { todaysAppointments: Appointment[]; calendarData: Array<{ appointment_date: string; count: number }>; upcomingFollowUps?: Patient[]; stats: { todayVisits: number; newPatientsToday: number; totalAppointmentsToday: number; totalPatients: number }; currentDate: { month: number; year: number; today: string } }
export interface PatientVisit { id: string; visit_date: string; appointment_time?: string; provider: string; visit_type: string; status: string; summary: string; procedures?: string[]; is_appointment?: boolean }
export interface PatientPrescription { id: string; patient_id: string; medication: string; dosage: string; frequency: string; duration: string; instructions: string; prescribed_at: string; prescribed_by: string }
export interface PatientMedicalReport { id: string; patient_id: string; file_name: string; mime_type: string; file_size: number; data_base64: string; description?: string; uploaded_at: string; uploaded_by: string }
export type LabDispatchStatus = 'queued' | 'provider-ready'
export interface PatientDispatchRecord { id: string; lab_order_id: string; channel: 'patient' | 'clinic' | 'lab'; recipient: string; status: LabDispatchStatus; created_at: string; note: string }
export interface PatientLabOrder { id: string; patient_id: string; order_number: string; ordered_at: string; tests: string; teeth_creation_service: string; lab_name: string; lab_email: string; lab_phone: string; instructions: string; copy_to_patient: boolean; copy_to_clinic: boolean; dispatch_status: LabDispatchStatus; dispatch_note: string; dispatch_history: PatientDispatchRecord[] }
export interface PatientProfile { patient: Patient; visits: PatientVisit[]; prescriptions: PatientPrescription[]; reports: PatientMedicalReport[]; lab_orders: PatientLabOrder[]; dispatch_history: PatientDispatchRecord[] }
export interface PrescriptionInput { patientId: string; medication: string; dosage: string; frequency: string; duration: string; instructions: string }
export interface PatientUpdateInput { firstName?: string; lastName?: string; email?: string | null; phone?: string | null; dateOfBirth?: string | null; gender?: string | null; notes?: string | null }
export interface MedicalReportInput { patientId: string; fileName: string; mimeType: string; fileSize: number; dataBase64: string; description?: string }
export interface LabOrderInput { patientId: string; orderNumber?: string; tests: string; teethCreationService: string; labName: string; labEmail: string; labPhone: string; instructions: string; copyToPatient: boolean; copyToClinic: boolean }
export type AppointmentStatus = 'scheduled' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show'
export interface AppointmentUpdateInput { patientId?: string; appointmentDate?: string; appointmentTime?: string; duration?: number; appointmentType?: string; status?: AppointmentStatus; reason?: string | null; notes?: string | null; followUpRequired?: boolean; followUpDate?: string | null }

function normalizePatientProfile(raw: { patient: Patient; appointments?: Array<Record<string, unknown>>; prescriptions?: Array<Record<string, unknown>>; reports?: Array<Record<string, unknown>>; labOrders?: Array<Record<string, unknown>>; dispatchHistory?: Array<Record<string, unknown>> }): PatientProfile {
  const appointments = raw.appointments || []
  const visits: PatientVisit[] = appointments.map((visit) => ({ id: String(visit.id), visit_date: String(visit.appointment_date || ''), appointment_time: visit.appointment_time ? String(visit.appointment_time) : undefined, provider: String(visit.provider || 'Clinic team'), visit_type: String(visit.appointment_type || 'Dental visit'), status: String(visit.status || 'scheduled'), summary: String(visit.reason || visit.notes || 'Visit recorded.'), procedures: Array.isArray(visit.procedures) ? visit.procedures as string[] : [], is_appointment: true }))
  const patient = { ...raw.patient, last_visit: raw.patient.last_visit || visits.filter((visit) => visit.status === 'completed').map((visit) => visit.visit_date).sort().at(-1) || null, next_appointment: raw.patient.next_appointment || visits.filter((visit) => !['cancelled', 'completed'].includes(visit.status) && visit.visit_date >= today).map((visit) => visit.visit_date).sort()[0] || null }
  const prescriptions: PatientPrescription[] = (raw.prescriptions || []).map((item) => ({ id: String(item.id), patient_id: String(item.patient_id || patient.id), medication: String(item.medication || item.medication_name || ''), dosage: String(item.dosage || ''), frequency: String(item.frequency || ''), duration: String(item.duration || ''), instructions: String(item.instructions || 'Use as directed.'), prescribed_at: String(item.prescribed_at || item.created_at || ''), prescribed_by: String(item.prescribed_by || 'Clinic team') }))
  const reports: PatientMedicalReport[] = (raw.reports || []).map((item) => ({ id: String(item.id), patient_id: String(item.patient_id || patient.id), file_name: String(item.file_name || item.attachment_name || 'Clinical report'), mime_type: String(item.mime_type || item.attachment_mime_type || 'application/octet-stream'), file_size: Number(item.file_size || item.attachment_size || 0), data_base64: String(item.data_base64 || ''), description: item.description ? String(item.description) : undefined, uploaded_at: String(item.uploaded_at || item.created_at || ''), uploaded_by: String(item.uploaded_by || 'Clinic team') }))
  const normalizeDispatch = (item: Record<string, unknown>): PatientDispatchRecord => ({ id: String(item.id), lab_order_id: String(item.lab_order_id || ''), channel: item.recipient_type === 'patient' ? 'patient' : item.recipient_type === 'clinic' ? 'clinic' : 'lab', recipient: String(item.recipient || ''), status: ['sent', 'processing'].includes(String(item.status)) ? 'provider-ready' : 'queued', created_at: String(item.created_at || ''), note: item.note ? String(item.note) : `Queued via ${String(item.channel || 'provider')} for provider processing.` })
  const allDispatches = (raw.dispatchHistory || []).map(normalizeDispatch)
  const lab_orders: PatientLabOrder[] = (raw.labOrders || []).map((item) => { const dispatch_history = Array.isArray(item.dispatch_history) ? (item.dispatch_history as Array<Record<string, unknown>>).map(normalizeDispatch) : allDispatches.filter((dispatch) => dispatch.lab_order_id === String(item.id)); return { id: String(item.id), patient_id: String(item.patient_id || patient.id), order_number: String(item.order_number || `LAB-${String(item.id).slice(0, 8)}`), ordered_at: String(item.ordered_at || item.created_at || ''), tests: String(item.tests || item.test_name || ''), teeth_creation_service: String(item.teeth_creation_service || ''), lab_name: String(item.lab_name || ''), lab_email: String(item.lab_email || ''), lab_phone: String(item.lab_phone || ''), instructions: String(item.instructions || ''), copy_to_patient: Boolean(item.copy_to_patient ?? true), copy_to_clinic: Boolean(item.copy_to_clinic ?? false), dispatch_status: item.dispatch_status === 'provider-ready' || item.status === 'processing' ? 'provider-ready' : 'queued', dispatch_note: String(item.dispatch_note || 'Queued for provider processing; delivery status is traceable in Dispatch history.'), dispatch_history } })
  return { patient, visits, prescriptions, reports, lab_orders, dispatch_history: allDispatches }
}

function makeLabOrderPdf(input: { orderNumber: string; patientId: string; tests: string; teethService: string; labName: string; instructions: string }) {
  const safe = (value: string) => value.replace(/[^\x20-\x7E]/g, '?').replace(/[()\\]/g, (character) => `\\${character}`)
  const lines = [`Dental laboratory order`, `Order: ${input.orderNumber}`, `Patient ID: ${input.patientId}`, `Lab: ${input.labName}`, `Tests: ${input.tests}`, `Teeth service: ${input.teethService || 'Not specified'}`, `Instructions: ${input.instructions || 'None provided'}`]
  const stream = [`BT`, `/F1 16 Tf`, `50 760 Td`, `(${safe(lines[0])}) Tj`, `/F1 10 Tf`, ...lines.slice(1).map((line) => `0 -28 Td (${safe(line)}) Tj`), `ET`, ''].join('\n')
  const objects = [`<< /Type /Catalog /Pages 2 0 R >>`, `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`, `<< /Length ${stream.length} >>\nstream\n${stream}endstream`, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`]
  let pdf = '%PDF-1.4\n'; const offsets = [0]
  objects.forEach((object, index) => { offsets.push(pdf.length); pdf += `${index + 1} 0 obj\n${object}\nendobj\n` })
  const xref = pdf.length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`
  return { base64: btoa(pdf), size: new TextEncoder().encode(pdf).length }
}

const localDateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const today = localDateKey(new Date())
const dateIn = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); return localDateKey(date) }
const DEMO_PATIENTS_KEY = 'agentfleet.demo.patients'
const DEMO_APPOINTMENTS_KEY = 'agentfleet.demo.appointments'
const DEMO_DENTIST_NOTES_KEY = 'agentfleet.demo.dentistNotes'
const DEMO_INVENTORY_KEY = 'agentfleet.demo.inventory'
const DEMO_SUPPORT_CHAT_KEY = 'agentfleet.demo.supportChat'
const DEMO_CLIENT_ALERTS_KEY = 'agentfleet.demo.clientAlerts'
const DEMO_PATIENT_PROFILES_KEY = 'agentfleet.demo.patientProfiles'
const mockPatients: Patient[] = [
  ['Aarav', 'Sharma', 'Active orthodontic treatment'], ['Meera', 'Cooper', 'Upcoming follow-up'], ['Kabir', 'Alexander', 'Needs filling review'], ['Ananya', 'Wilson', 'New patient'], ['Rohan', 'Fox', 'Requires treatment plan'],
  ['Isha', 'Howard', 'Preventive care'], ['Vihaan', 'Williamson', 'Implant review'], ['Tara', 'Simmons', 'Follow-up needed'], ['Dev', 'Patel', 'Overdue cleaning'], ['Zoya', 'Khan', 'Minor patient; guardian consent required'],
].map(([first_name, last_name, notes], index) => ({ id: `demo-patient-${index + 1}`, first_name, last_name, notes, phone: `+91-900000000${index + 1}`, email: `${first_name.toLowerCase()}@example.test`, gender: index % 2 ? 'Female' : 'Male', last_visit: index === 3 ? null : dateIn(-(index + 2)), next_appointment: [1, 4, 6, 7, 9].includes(index) ? dateIn(index + 3) : null }))
const mockAppointments: Appointment[] = [
  ['08:00:00', 0, 'Checkup', 'Regular checkup'], ['10:00:00', 1, 'Cleaning', 'Preventive cleaning'], ['14:00:00', 2, 'Cavity Filling', 'Filling review'], ['16:00:00', 3, 'Consultation', 'New patient assessment'],
].map(([appointment_time, patientIndex, appointment_type, reason], index) => { const patient = mockPatients[Number(patientIndex)]; return { id: `demo-appointment-${index + 1}`, patient_id: patient.id, appointment_date: today, appointment_time: String(appointment_time), duration: 30, appointment_type: String(appointment_type), status: index === 2 ? 'in_progress' : 'scheduled', reason: String(reason), notes: '', first_name: patient.first_name, last_name: patient.last_name, phone: patient.phone || '', gender: patient.gender || '' } })
const mockSettings: ClinicSettings = { clinic_name: 'V.P.S. Dental & Oral Care', clinic_email: 'info@vpsdental.com', phone: '+91-XXXXXXXXXX', address: { city: 'Kanpur', state: 'Uttar Pradesh', country: 'India' }, branding: { primaryColor: '#005db6', accentColor: '#a23858', logo: '🦷' }, working_hours: { monday: '09:00-18:00', saturday: '10:00-14:00' }, appointment_settings: { duration: 45, bufferMinutes: 10, emergencySlots: 2 }, notifications: { emailAlerts: true, smsReminders: true }, timezone: 'Asia/Kolkata' }
const mockInventory: InventoryItem[] = [
  { id: 'demo-1', name: 'Dental Examination Kit', category: 'Diagnostic', quantity: 24, reorder_level: 10, unit: 'kits', is_active: true, low_stock: false },
  { id: 'demo-2', name: 'Composite Resin A2', category: 'Restorative', quantity: 8, reorder_level: 10, unit: 'syringes', is_active: true, low_stock: true },
  { id: 'demo-3', name: 'Nitrile Examination Gloves', category: 'Consumables', quantity: 12, reorder_level: 15, unit: 'boxes', is_active: true, low_stock: true },
]
const mockHospitals: HospitalDirectory[] = [
  { id: 'hospital-own-1', name: 'V.P.S. Dental & Oral Care', relationship: 'own', specialty: 'Dental & Oral Care', address: '12 Civil Lines', city: 'Kanpur', contact_name: 'Dr. Rajeev Pratap Singh', contact_phone: '+91 90000 00001', is_active: true },
  { id: 'hospital-partner-1', name: 'Regency Superspeciality Hospital', relationship: 'partner', specialty: 'Oral Surgery & Maxillofacial Care', address: 'A-2 Sarvodaya Nagar', city: 'Kanpur', contact_name: 'Referral Desk', contact_phone: '+91 90000 00002', is_active: true },
  { id: 'hospital-partner-2', name: 'Kalyanpur Diagnostic Centre', relationship: 'partner', specialty: 'Imaging & Diagnostics', address: 'Main GT Road, Kalyanpur', city: 'Kanpur', contact_name: 'Coordination Desk', contact_phone: '+91 90000 00003', is_active: true },
]
const mockClientAlerts: NotificationAlert[] = [
  { id: 'demo-alert-1', kind: 'message', title: 'New patient message', body: 'Meera Cooper asked whether her follow-up can be moved to Friday.', customer_name: 'Meera Cooper', is_read: false, created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString() },
  { id: 'demo-alert-2', kind: 'email', title: 'Email from Aarav Sharma', body: 'Aarav shared an updated insurance document for his appointment.', customer_name: 'Aarav Sharma', is_read: false, created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString() },
  { id: 'demo-alert-3', kind: 'call', title: 'Missed call from Kabir Alexander', body: 'A customer called the clinic and requested a callback.', customer_name: 'Kabir Alexander', is_read: true, created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString() },
]

const demoProfileFor = (patient: Patient, index: number): PatientProfile => {
  const createdAt = new Date(Date.now() - (index + 1) * 86400000).toISOString()
  const visit: PatientVisit = { id: `demo-visit-${index + 1}`, visit_date: patient.last_visit || dateIn(-(index + 2)), provider: 'Dr. Rajeev Pratap Singh', visit_type: index % 2 ? 'Preventive check-up' : 'Treatment review', status: 'completed', summary: index % 2 ? 'Routine oral examination and cleaning completed.' : 'Reviewed treatment progress and updated care plan.', procedures: index % 2 ? ['Examination', 'Prophylaxis'] : ['Clinical assessment'] }
  const prescription: PatientPrescription = { id: `demo-prescription-${index + 1}`, patient_id: patient.id, medication: index % 2 ? 'Chlorhexidine mouthwash' : 'Fluoride toothpaste', dosage: index % 2 ? '10 ml' : 'Pea-sized amount', frequency: index % 2 ? 'Twice daily' : 'At bedtime', duration: '14 days', instructions: 'Use as directed and report any sensitivity or adverse reaction.', prescribed_at: createdAt, prescribed_by: 'Dr. Rajeev Pratap Singh' }
  const report: PatientMedicalReport = { id: `demo-report-${index + 1}`, patient_id: patient.id, file_name: index % 2 ? 'bitewing-review.txt' : 'oral-examination-notes.txt', mime_type: 'text/plain', file_size: 48, data_base64: 'U2FtcGxlIGNsaW5pY2FsIHJlY29yZCBmb3IgZGVtbyBtb2RlLg==', description: 'Sample clinical record for demo mode.', uploaded_at: createdAt, uploaded_by: 'V.P.S. Dental & Oral Care' }
  const sampleDispatch: PatientDispatchRecord = { id: `demo-dispatch-${index + 1}`, lab_order_id: `demo-lab-order-${index + 1}`, channel: 'lab', recipient: 'BrightSmile Dental Lab', status: 'provider-ready', created_at: createdAt, note: 'Prepared for provider handoff; no external delivery was attempted.' }
  const sampleLab: PatientLabOrder = { id: sampleDispatch.lab_order_id, patient_id: patient.id, order_number: `LAB-DEMO-${index + 1}`, ordered_at: createdAt, tests: 'Bitewing radiographs', teeth_creation_service: 'Crown shade matching', lab_name: 'BrightSmile Dental Lab', lab_email: 'orders@brightsmile.example', lab_phone: '+91 90000 01001', instructions: 'Confirm shade with clinic before fabrication.', copy_to_patient: true, copy_to_clinic: true, dispatch_status: 'provider-ready', dispatch_note: 'Provider-ready for manual handoff. This demo does not claim real provider delivery.', dispatch_history: [sampleDispatch] }
  return { patient, visits: [visit], prescriptions: [prescription], reports: [report], lab_orders: index === 0 ? [sampleLab] : [], dispatch_history: index === 0 ? [sampleDispatch] : [] }
}

function readDemoCollection<T>(key: string, fallback: T[]): T[] {
  try {
    const stored = JSON.parse(localStorage.getItem(key) || 'null')
    return Array.isArray(stored) ? stored as T[] : fallback
  } catch {
    return fallback
  }
}

function writeDemoCollection<T>(key: string, items: T[]) {
  localStorage.setItem(key, JSON.stringify(items))
}

const getDemoPatients = () => readDemoCollection<Patient>(DEMO_PATIENTS_KEY, mockPatients)
const getDemoAppointments = () => readDemoCollection<Appointment>(DEMO_APPOINTMENTS_KEY, mockAppointments)
const getDemoAlerts = () => readDemoCollection<NotificationAlert>(DEMO_CLIENT_ALERTS_KEY, mockClientAlerts)
const getDemoPatientProfiles = () => {
  const patients = getDemoPatients()
  const stored = readDemoCollection<PatientProfile>(DEMO_PATIENT_PROFILES_KEY, [])
  const profiles = patients.map((patient, index) => stored.find((profile) => profile.patient.id === patient.id) || demoProfileFor(patient, index))
  if (stored.length !== profiles.length) writeDemoCollection(DEMO_PATIENT_PROFILES_KEY, profiles)
  return profiles
}
const demoAppointmentVisit = (appointment: Appointment): PatientVisit => ({ id: appointment.id, visit_date: appointment.appointment_date, appointment_time: appointment.appointment_time, provider: 'Clinic team', visit_type: appointment.appointment_type, status: appointment.status, summary: appointment.reason || appointment.notes || 'Appointment recorded.', procedures: [], is_appointment: true })
const getDemoPatientProfile = (id: string) => {
  const profile = getDemoPatientProfiles().find((item) => item.patient.id === id)
  if (!profile) throw new Error('Patient profile not found')
  const appointments = getDemoAppointments().filter((item) => item.patient_id === id)
  const appointmentIds = new Set(appointments.map((item) => item.id))
  const visits = [...appointments.map(demoAppointmentVisit), ...profile.visits.filter((visit) => !appointmentIds.has(visit.id))]
  const nextAppointment = appointments.filter((item) => !['cancelled', 'completed'].includes(item.status) && item.appointment_date >= today).sort((a, b) => `${a.appointment_date} ${a.appointment_time}`.localeCompare(`${b.appointment_date} ${b.appointment_time}`))[0]
  return { ...profile, patient: { ...profile.patient, next_appointment: nextAppointment?.appointment_date || null }, visits }
}
const inventoryWithStock = (item: InventoryItem): InventoryItem => ({ ...item, is_active: item.is_active !== false, low_stock: item.quantity <= item.reorder_level })
const getDemoInventory = (search = '', includeInactive = false) => {
  const stored = readDemoCollection<InventoryItem>(DEMO_INVENTORY_KEY, mockInventory).map(inventoryWithStock)
  const needle = search.trim().toLowerCase()
  return stored.filter((item) => (includeInactive || item.is_active !== false) && `${item.name} ${item.category}`.toLowerCase().includes(needle))
}
const oneMonthFrom = (base = new Date()) => { const expiration = new Date(base); expiration.setMonth(expiration.getMonth() + 1); return expiration.toISOString() }
const getDemoDentistNotes = () => {
  const stored = readDemoCollection<DentistNote>(DEMO_DENTIST_NOTES_KEY, [])
  const now = Date.now()
  const normalized = stored.map((note) => ({ ...note, expires_at: note.expires_at || oneMonthFrom(note.created_at ? new Date(note.created_at) : new Date()), is_active: note.is_active !== false }))
  const updated = normalized.map((note) => note.is_active && Date.parse(note.expires_at) <= now ? { ...note, is_active: false } : note)
  if (JSON.stringify(stored) !== JSON.stringify(updated)) writeDemoCollection(DEMO_DENTIST_NOTES_KEY, updated)
  return updated.filter((note) => note.is_active)
}

function getDemoDashboardData(): DashboardData {
  const patients = getDemoPatients()
  const appointments = getDemoAppointments()
  const todaysAppointments = appointments.filter((appointment) => appointment.appointment_date === today)
  const counts = new Map<string, number>()
  appointments.forEach((appointment) => counts.set(appointment.appointment_date, (counts.get(appointment.appointment_date) || 0) + 1))
  return {
    todaysAppointments,
    calendarData: [...counts.entries()].map(([appointment_date, count]) => ({ appointment_date, count })),
    upcomingFollowUps: patients.filter((patient) => patient.next_appointment).slice(0, 10),
    stats: {
      todayVisits: new Set(todaysAppointments.map((appointment) => appointment.patient_id)).size,
      newPatientsToday: patients.filter((patient) => todaysAppointments.some((appointment) => appointment.patient_id === patient.id && !patient.last_visit)).length,
      totalAppointmentsToday: todaysAppointments.length,
      totalPatients: patients.length,
    },
    currentDate: { month: new Date().getMonth() + 1, year: new Date().getFullYear(), today },
  }
}

export class DashboardService {
  private static async request<T>(path: string, options: RequestInit = {}): Promise<T> {
    const token = localStorage.getItem('accessToken')
    const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
    const body = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(body.message || `Request failed (${response.status})`)
    return body.data as T
  }

  static async getDashboardData(): Promise<DashboardData> { try { return await this.request<DashboardData>('/api/v1/patients/dashboard') } catch (error) { if (!DEMO_MODE) throw error; console.warn('Using explicit demo dashboard data', error); return getDemoDashboardData() } }
  static async getPatients(search = '', limit = 25, offset = 0): Promise<{ data: Patient[]; total: number }> { try { const query = new URLSearchParams({ limit: String(limit), offset: String(offset), ...(search ? { search } : {}) }); const response = await this.requestBody<{ data: Patient[]; meta?: { total?: number } }>(`/api/v1/patients/patients?${query}`); return { data: response.data, total: response.meta?.total ?? response.data.length } } catch (error) { if (!DEMO_MODE) throw error; const needle = search.toLowerCase(); const filtered = getDemoPatients().filter((patient) => `${patient.first_name} ${patient.last_name} ${patient.phone} ${patient.email}`.toLowerCase().includes(needle)); return { data: filtered.slice(offset, offset + limit), total: filtered.length } } }
  static async updatePatient(id: string, changes: PatientUpdateInput): Promise<Patient> { try { return await this.request<Patient>(`/api/v1/patients/patients/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(changes) }) } catch (error) { if (!DEMO_MODE) throw error; const current = getDemoPatients(); const existing = current.find((item) => item.id === id); if (!existing) throw new Error('Patient not found'); const updated = { ...existing, first_name: changes.firstName ?? existing.first_name, last_name: changes.lastName ?? existing.last_name, email: changes.email ?? existing.email, phone: changes.phone ?? existing.phone, date_of_birth: changes.dateOfBirth ?? existing.date_of_birth, notes: changes.notes ?? existing.notes }; writeDemoCollection(DEMO_PATIENTS_KEY, current.map((item) => item.id === id ? updated : item)); const profiles = getDemoPatientProfiles().map((item) => item.patient.id === id ? { ...item, patient: { ...item.patient, ...updated } } : item); writeDemoCollection(DEMO_PATIENT_PROFILES_KEY, profiles); return updated } }
  static async getPatientProfile(id: string): Promise<PatientProfile> { try { const raw = await this.request<{ patient: Patient; appointments?: Array<Record<string, unknown>>; prescriptions?: Array<Record<string, unknown>>; reports?: Array<Record<string, unknown>>; labOrders?: Array<Record<string, unknown>>; dispatchHistory?: Array<Record<string, unknown>> }>(`/api/v1/patients/patients/${encodeURIComponent(id)}/profile`); return normalizePatientProfile(raw) } catch (error) { if (!DEMO_MODE) throw error; return getDemoPatientProfile(id) } }
  static async createPrescription(input: PrescriptionInput): Promise<PatientPrescription> { try { const result = await this.request<Record<string, unknown>>(`/api/v1/patients/patients/${encodeURIComponent(input.patientId)}/prescriptions`, { method: 'POST', body: JSON.stringify(input) }); return normalizePatientProfile({ patient: {} as Patient, prescriptions: [result] }).prescriptions[0] } catch (error) { if (!DEMO_MODE) throw error; const profile = await this.getPatientProfile(input.patientId); const prescription: PatientPrescription = { id: `demo-prescription-${Date.now()}`, patient_id: input.patientId, medication: input.medication, dosage: input.dosage, frequency: input.frequency, duration: input.duration, instructions: input.instructions, prescribed_at: new Date().toISOString(), prescribed_by: 'Dr. Rajeev Pratap Singh' }; const profiles = getDemoPatientProfiles().map((item) => item.patient.id === input.patientId ? { ...profile, prescriptions: [prescription, ...profile.prescriptions] } : item); writeDemoCollection(DEMO_PATIENT_PROFILES_KEY, profiles); return prescription } }
  static async createMedicalReport(input: MedicalReportInput): Promise<PatientMedicalReport> { try { return await this.request<PatientMedicalReport>(`/api/v1/patients/patients/${encodeURIComponent(input.patientId)}/reports`, { method: 'POST', body: JSON.stringify({ title: input.fileName, attachmentName: input.fileName, attachmentMimeType: input.mimeType, attachmentData: input.dataBase64, description: input.description }) }) } catch (error) { if (!DEMO_MODE) throw error; const profile = await this.getPatientProfile(input.patientId); const report: PatientMedicalReport = { id: `demo-report-${Date.now()}`, patient_id: input.patientId, file_name: input.fileName, mime_type: input.mimeType, file_size: input.fileSize, data_base64: input.dataBase64, description: input.description, uploaded_at: new Date().toISOString(), uploaded_by: 'V.P.S. Dental & Oral Care' }; const profiles = getDemoPatientProfiles().map((item) => item.patient.id === input.patientId ? { ...profile, reports: [report, ...profile.reports] } : item); writeDemoCollection(DEMO_PATIENT_PROFILES_KEY, profiles); return report } }
  static async createLabOrder(input: LabOrderInput): Promise<PatientLabOrder> { try { const orderNumber = input.orderNumber || `LAB-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`; const attachment = makeLabOrderPdf({ orderNumber, patientId: input.patientId, tests: input.tests, teethService: input.teethCreationService, labName: input.labName, instructions: input.instructions }); const result = await this.request<Record<string, unknown>>(`/api/v1/patients/patients/${encodeURIComponent(input.patientId)}/lab-orders`, { method: 'POST', body: JSON.stringify({ ...input, orderNumber, testName: input.tests, copyToPatient: input.copyToPatient, copyToClinic: input.copyToClinic, attachmentName: `${orderNumber}.pdf`, attachmentMimeType: 'application/pdf', attachmentSize: attachment.size, attachmentData: attachment.base64 }) }); return normalizePatientProfile({ patient: {} as Patient, labOrders: [result] }).lab_orders[0] } catch (error) { if (!DEMO_MODE) throw error; const profile = await this.getPatientProfile(input.patientId); const createdAt = new Date().toISOString(); const orderId = `demo-lab-order-${Date.now()}`; const orderNumber = input.orderNumber || `LAB-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`; const dispatchHistory: PatientDispatchRecord[] = [{ id: `${orderId}-lab`, lab_order_id: orderId, channel: 'lab', recipient: input.labEmail || input.labName, status: 'provider-ready', created_at: createdAt, note: 'Prepared for provider handoff; no external delivery was attempted.' }]; if (input.copyToPatient) dispatchHistory.push({ id: `${orderId}-patient`, lab_order_id: orderId, channel: 'patient', recipient: profile.patient.email || profile.patient.phone || 'Patient contact', status: 'queued', created_at: createdAt, note: 'Patient copy queued for clinic review.' }); if (input.copyToClinic) dispatchHistory.push({ id: `${orderId}-clinic`, lab_order_id: orderId, channel: 'clinic', recipient: 'Clinic records', status: 'queued', created_at: createdAt, note: 'Clinic copy queued for records.' }); const order: PatientLabOrder = { id: orderId, patient_id: input.patientId, order_number: orderNumber, ordered_at: createdAt, tests: input.tests, teeth_creation_service: input.teethCreationService, lab_name: input.labName, lab_email: input.labEmail, lab_phone: input.labPhone, instructions: input.instructions, copy_to_patient: input.copyToPatient, copy_to_clinic: input.copyToClinic, dispatch_status: 'provider-ready', dispatch_note: 'Provider-ready for manual handoff. This demo does not claim real provider delivery.', dispatch_history: dispatchHistory }; const profiles = getDemoPatientProfiles().map((item) => item.patient.id === input.patientId ? { ...profile, lab_orders: [order, ...profile.lab_orders], dispatch_history: [...dispatchHistory, ...profile.dispatch_history] } : item); writeDemoCollection(DEMO_PATIENT_PROFILES_KEY, profiles); return order } }

  static async downloadMedicalReport(patientId: string, reportId: string, fileName: string): Promise<void> {
    try {
      const token = localStorage.getItem('accessToken'); const response = await fetch(`${API_BASE_URL}/api/v1/patients/patients/${encodeURIComponent(patientId)}/reports/${encodeURIComponent(reportId)}/download`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error('Unable to download report'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url)
    } catch (error) {
      if (!DEMO_MODE) throw error
      const report = (await this.getPatientProfile(patientId)).reports.find((item) => item.id === reportId); if (!report?.data_base64) throw new Error('Report attachment is not available'); const binary = atob(report.data_base64); const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: report.mime_type })); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url)
    }
  }

  static async downloadLabOrder(patientId: string, orderId: string, fileName: string): Promise<void> {
    try {
      const token = localStorage.getItem('accessToken'); const response = await fetch(`${API_BASE_URL}/api/v1/patients/patients/${encodeURIComponent(patientId)}/lab-orders/${encodeURIComponent(orderId)}/download`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error('Unable to download lab order PDF'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url)
    } catch (error) {
      if (!DEMO_MODE) throw error
      const order = (await this.getPatientProfile(patientId)).lab_orders.find((item) => item.id === orderId); if (!order) throw new Error('Lab order not found'); const pdf = makeLabOrderPdf({ orderNumber: order.order_number, patientId, tests: order.tests, teethService: order.teeth_creation_service, labName: order.lab_name, instructions: order.instructions }); const binary = atob(pdf.base64); const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: 'application/pdf' })); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url)
    }
  }
  static async updateAppointment(id: string, changes: AppointmentUpdateInput): Promise<Appointment> { try { return await this.request<Appointment>(`/api/v1/patients/appointments/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(changes) }) } catch (error) { if (!DEMO_MODE) throw error; const current = getDemoAppointments(); const existing = current.find((item) => item.id === id); if (!existing) throw new Error('Appointment not found'); const updated = { ...existing, appointment_date: changes.appointmentDate ?? existing.appointment_date, appointment_time: changes.appointmentTime ?? existing.appointment_time, duration: changes.duration ?? existing.duration, appointment_type: changes.appointmentType ?? existing.appointment_type, status: changes.status ?? existing.status, reason: changes.reason ?? existing.reason, notes: changes.notes ?? existing.notes }; writeDemoCollection(DEMO_APPOINTMENTS_KEY, current.map((item) => item.id === id ? updated : item)); const patientAppointments = current.map((item) => item.id === id ? updated : item).filter((item) => item.patient_id === updated.patient_id); const nextAppointment = patientAppointments.filter((item) => !['cancelled', 'completed'].includes(item.status) && item.appointment_date >= today).sort((a, b) => `${a.appointment_date} ${a.appointment_time}`.localeCompare(`${b.appointment_date} ${b.appointment_time}`))[0]?.appointment_date || null; const patients = getDemoPatients(); writeDemoCollection(DEMO_PATIENTS_KEY, patients.map((patient) => patient.id === updated.patient_id ? { ...patient, next_appointment: nextAppointment } : patient)); return updated } }
  static async getAppointments(from: string, to: string): Promise<Appointment[]> { try { return await this.request<Appointment[]>(`/api/v1/patients/appointments?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`) } catch (error) { if (!DEMO_MODE) throw error; return getDemoAppointments().filter((appointment) => appointment.appointment_date >= from && appointment.appointment_date <= to) } }
  static async getTodaysAppointments(): Promise<Appointment[]> { try { return await this.request<Appointment[]>('/api/v1/patients/appointments/today') } catch (error) { if (!DEMO_MODE) throw error; return getDemoAppointments().filter((appointment) => appointment.appointment_date === today) } }
  static async getDentistNotes(): Promise<DentistNote[]> { try { return await this.request<DentistNote[]>('/api/v1/patients/notes') } catch (error) { if (!DEMO_MODE) throw error; return getDemoDentistNotes() } }
  static async createDentistNote(input: DentistNoteInput): Promise<DentistNote> { try { return await this.request<DentistNote>('/api/v1/patients/notes', { method: 'POST', body: JSON.stringify(input) }) } catch (error) { if (!DEMO_MODE) throw error; const now = new Date().toISOString(); const note: DentistNote = { id: `demo-note-${Date.now()}`, title: input.title, content: input.content, expires_at: input.expiresAt || oneMonthFrom(), is_active: true, created_at: now, updated_at: now }; const next = [note, ...getDemoDentistNotes()]; writeDemoCollection(DEMO_DENTIST_NOTES_KEY, next); return note } }
  static async updateDentistNote(id: string, input: DentistNoteInput): Promise<DentistNote> { try { return await this.request<DentistNote>(`/api/v1/patients/notes/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(input) }) } catch (error) { if (!DEMO_MODE) throw error; const current = getDemoDentistNotes(); const existing = current.find((note) => note.id === id); if (!existing) throw new Error('Dentist note not found'); const note = { ...existing, ...input, expires_at: input.expiresAt || oneMonthFrom(), is_active: true, updated_at: new Date().toISOString() }; writeDemoCollection(DEMO_DENTIST_NOTES_KEY, current.map((item) => item.id === id ? note : item)); return note } }
  static async deleteDentistNote(id: string): Promise<void> { try { await this.request<{ id: string }>(`/api/v1/patients/notes/${encodeURIComponent(id)}`, { method: 'DELETE' }) } catch (error) { if (!DEMO_MODE) throw error; const current = readDemoCollection<DentistNote>(DEMO_DENTIST_NOTES_KEY, []); if (!current.some((note) => note.id === id && note.is_active !== false)) throw new Error('Dentist note not found'); writeDemoCollection(DEMO_DENTIST_NOTES_KEY, current.map((note) => note.id === id ? { ...note, is_active: false, updated_at: new Date().toISOString() } : note)) } }
  static async createBooking(bookingData: unknown) { try { return await this.request<{ patientId: string; appointmentId: string }>('/api/v1/patients/bookings', { method: 'POST', body: JSON.stringify(bookingData) }) } catch (error) { if (!DEMO_MODE) throw error; const input = bookingData as Record<string, string>; const timestamp = Date.now(); const patientId = `demo-patient-${timestamp}`; const appointmentId = `demo-appointment-${timestamp}`; const patient: Patient = { id: patientId, first_name: input.firstName, last_name: input.lastName, phone: input.phone, email: input.email, gender: input.gender, date_of_birth: input.dateOfBirth || undefined, last_visit: null, next_appointment: input.appointmentDate }; const appointment: Appointment = { id: appointmentId, patient_id: patientId, appointment_date: input.appointmentDate, appointment_time: input.appointmentTime, duration: 30, appointment_type: input.appointmentType, status: 'scheduled', reason: input.reason, notes: input.notes || '', first_name: patient.first_name, last_name: patient.last_name, phone: patient.phone || '', gender: patient.gender || '' }; writeDemoCollection(DEMO_PATIENTS_KEY, [...getDemoPatients(), patient]); writeDemoCollection(DEMO_APPOINTMENTS_KEY, [...getDemoAppointments(), appointment]); return { patientId, appointmentId } } }
  static async getSettings(): Promise<ClinicSettings | null> { try { return await this.request<ClinicSettings | null>('/api/v1/patients/settings') } catch (error) { if (!DEMO_MODE) throw error; try { return JSON.parse(localStorage.getItem('clinicSettingsDraft') || 'null') as ClinicSettings | null || mockSettings } catch { return mockSettings } } }
  static async updateSettings(settings: Record<string, unknown>): Promise<ClinicSettings> { try { return await this.request<ClinicSettings>('/api/v1/patients/settings', { method: 'PUT', body: JSON.stringify(settings) }) } catch (error) { if (!DEMO_MODE) throw error; const current = await this.getSettings() || mockSettings; const next = { ...current, clinic_name: settings.clinicName || current.clinic_name, clinic_email: settings.clinicEmail || current.clinic_email, notifications: settings.notifications || current.notifications } as ClinicSettings; localStorage.setItem('clinicSettingsDraft', JSON.stringify(next)); return next } }
  static async getHospitalDirectory(search = ''): Promise<HospitalDirectory[]> { try { return await this.request<HospitalDirectory[]>(`/api/v1/patients/hospitals?search=${encodeURIComponent(search)}`) } catch (error) { if (!DEMO_MODE) throw error; const needle = search.trim().toLowerCase(); return mockHospitals.filter((hospital) => `${hospital.name} ${hospital.relationship} ${hospital.specialty} ${hospital.city}`.toLowerCase().includes(needle)) } }
  static async getClientAlerts(unreadOnly = false): Promise<NotificationAlert[]> { try { return await this.request<NotificationAlert[]>(`/api/v1/patients/notifications?unreadOnly=${unreadOnly}`) } catch (error) { if (!DEMO_MODE) throw error; return getDemoAlerts().filter((alert) => !unreadOnly || !alert.is_read) } }
  static async markClientAlertRead(id: string): Promise<void> { try { await this.request<{ id: string }>(`/api/v1/patients/notifications/${encodeURIComponent(id)}/read`, { method: 'PATCH' }) } catch (error) { if (!DEMO_MODE) throw error; const alerts = getDemoAlerts(); writeDemoCollection(DEMO_CLIENT_ALERTS_KEY, alerts.map((alert) => alert.id === id ? { ...alert, is_read: true } : alert)) } }
  static async getInventory(search = ''): Promise<InventoryItem[]> { try { return await this.request<InventoryItem[]>(`/api/v1/patients/inventory?search=${encodeURIComponent(search)}`) } catch (error) { if (!DEMO_MODE) throw error; return getDemoInventory(search) } }
  static async getInventoryHistory(search = ''): Promise<InventoryItem[]> { try { return await this.request<InventoryItem[]>(`/api/v1/patients/inventory/history?search=${encodeURIComponent(search)}`) } catch (error) { if (!DEMO_MODE) throw error; return getDemoInventory(search, true).filter((item) => item.is_active === false) } }
  static async createInventory(item: InventoryInput): Promise<InventoryItem> { try { return await this.request<InventoryItem>('/api/v1/patients/inventory', { method: 'POST', body: JSON.stringify(item) }) } catch (error) { if (!DEMO_MODE) throw error; const created = inventoryWithStock({ id: `demo-inventory-${Date.now()}`, ...item, reorder_level: item.reorderLevel, is_active: true }); const current = readDemoCollection<InventoryItem>(DEMO_INVENTORY_KEY, mockInventory); writeDemoCollection(DEMO_INVENTORY_KEY, [...current, created]); return created } }
  static async updateInventory(id: string, changes: Partial<InventoryInput>): Promise<InventoryItem> { try { return await this.request<InventoryItem>(`/api/v1/patients/inventory/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(changes) }) } catch (error) { if (!DEMO_MODE) throw error; const current = readDemoCollection<InventoryItem>(DEMO_INVENTORY_KEY, mockInventory); const existing = current.find((item) => item.id === id && item.is_active !== false); if (!existing) throw new Error('Inventory item not found'); const updated = inventoryWithStock({ ...existing, ...changes, reorder_level: changes.reorderLevel ?? existing.reorder_level }); writeDemoCollection(DEMO_INVENTORY_KEY, current.map((item) => item.id === id ? updated : item)); return updated } }
  static async deleteInventory(id: string): Promise<void> { try { await this.request<{ id: string }>(`/api/v1/patients/inventory/${encodeURIComponent(id)}`, { method: 'DELETE' }) } catch (error) { if (!DEMO_MODE) throw error; const current = readDemoCollection<InventoryItem>(DEMO_INVENTORY_KEY, mockInventory); if (!current.some((item) => item.id === id && item.is_active !== false)) throw new Error('Inventory item not found'); writeDemoCollection(DEMO_INVENTORY_KEY, current.map((item) => item.id === id ? { ...item, is_active: false } : item)) } }
  static async getSupportChat(): Promise<SupportChat | null> { try { return await this.request<SupportChat | null>('/api/v1/patients/support/chat') } catch (error) { if (!DEMO_MODE) throw error; return readDemoCollection<SupportChat>(DEMO_SUPPORT_CHAT_KEY, [])[0] || null } }
  static async createSupportConversation(subject = 'Hospital support'): Promise<SupportChat> { try { return await this.request<SupportChat>('/api/v1/patients/support/conversations', { method: 'POST', body: JSON.stringify({ subject }) }) } catch (error) { if (!DEMO_MODE) throw error; const now = new Date().toISOString(); const chat: SupportChat = { conversation: { id: `demo-support-${Date.now()}`, subject, status: 'open', created_by: 'demo-user', created_at: now, updated_at: now }, messages: [] }; writeDemoCollection(DEMO_SUPPORT_CHAT_KEY, [chat]); return chat } }
  static async sendSupportMessage(conversationId: string, body: string): Promise<SupportMessage> { try { return await this.request<SupportMessage>(`/api/v1/patients/support/conversations/${encodeURIComponent(conversationId)}/messages`, { method: 'POST', body: JSON.stringify({ body }) }) } catch (error) { if (!DEMO_MODE) throw error; const chats = readDemoCollection<SupportChat>(DEMO_SUPPORT_CHAT_KEY, []); const chat = chats.find((item) => item.conversation?.id === conversationId); if (!chat || !chat.conversation) throw new Error('Support conversation not found'); const message: SupportMessage = { id: `demo-support-message-${Date.now()}`, conversation_id: conversationId, sender_id: 'demo-user', sender_name: 'You', sender_role: 'client', body, created_at: new Date().toISOString() }; chat.messages = [...chat.messages, message]; chat.conversation.updated_at = message.created_at; writeDemoCollection(DEMO_SUPPORT_CHAT_KEY, chats); return message } }

  private static async requestBody<T>(path: string, options: RequestInit = {}): Promise<T> {
    const token = localStorage.getItem('accessToken')
    const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
    const body = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(body.message || `Request failed (${response.status})`)
    return body as T
  }
}