import { useCallback, useEffect, useState, type ChangeEvent, type FormEvent } from 'react'
import { ArrowLeft, CalendarDays, CheckCircle2, ClipboardList, Clock3, Download, FileText, FlaskConical, MapPin, Pill, Plus, Stethoscope, Upload, UserRound, X } from 'lucide-react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { DashboardService, type LabOrderInput, type PatientLabOrder, type PatientProfile, type PatientVisit, type PrescriptionInput } from '../services/dashboardService'

type Tab = 'overview' | 'visits' | 'prescriptions' | 'reports' | 'labs' | 'dispatch'
const tabs: Array<{ id: Tab; label: string; icon: typeof FileText }> = [{ id: 'overview', label: 'Overview', icon: UserRound }, { id: 'visits', label: 'Visit history', icon: CalendarDays }, { id: 'prescriptions', label: 'Prescriptions', icon: Pill }, { id: 'reports', label: 'Medical reports', icon: FileText }, { id: 'labs', label: 'Lab orders', icon: FlaskConical }, { id: 'dispatch', label: 'Dispatch history', icon: ClipboardList }]
const inputClass = 'mt-1 h-11 w-full rounded-xl border border-[#c2c6d4]/60 bg-white px-3 text-sm text-[#151c23] outline-none focus:ring-2 focus:ring-[#005db6]/20'
const dateLabel = (value?: string | null) => value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'Not recorded'
const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`

export default function PatientProfilePage() {
  const { id } = useParams<{ id: string }>()
  const location = useLocation()
  const navigate = useNavigate()
  const fromCustomerDetails = location.pathname.startsWith('/dental-client/customers/')
  const [profile, setProfile] = useState<PatientProfile | null>(null)
  const [tab, setTab] = useState<Tab>('overview')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState('')
  const [selectedPrintOrder, setSelectedPrintOrder] = useState<PatientLabOrder | null>(null)
  const [printPending, setPrintPending] = useState(false)
  const [completionVisit, setCompletionVisit] = useState<PatientVisit | null>(null)
  const [completionNotes, setCompletionNotes] = useState('')
  const [prescription, setPrescription] = useState<Omit<PrescriptionInput, 'patientId'>>({ medication: '', dosage: '', frequency: '', duration: '', instructions: '' })
  const [report, setReport] = useState({ fileName: '', mimeType: '', fileSize: 0, dataBase64: '', description: '' })
  const [lab, setLab] = useState<Omit<LabOrderInput, 'patientId'>>({ tests: '', teethCreationService: '', labName: '', labEmail: '', labPhone: '', instructions: '', copyToPatient: true, copyToClinic: true })
  const [customerDraft, setCustomerDraft] = useState({ firstName: '', lastName: '', email: '', phone: '', notes: '' })

  const loadProfile = useCallback(async () => { if (!id) return; setLoading(true); setError(null); try { setProfile(await DashboardService.getPatientProfile(id)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load patient profile') } finally { setLoading(false) } }, [id])
  useEffect(() => { void loadProfile() }, [loadProfile])
  useEffect(() => { if (profile) setCustomerDraft({ firstName: profile.patient.first_name, lastName: profile.patient.last_name, email: profile.patient.email || '', phone: profile.patient.phone || '', notes: profile.patient.notes || '' }) }, [profile])
  useEffect(() => { if (!printPending || !selectedPrintOrder) return; setPrintPending(false); window.setTimeout(() => window.print(), 0) }, [printPending, selectedPrintOrder])
  const save = async (action: () => Promise<unknown>, message: string) => { setSaving(true); setError(null); setNotice(''); try { await action(); setNotice(message); await loadProfile() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save this record') } finally { setSaving(false) } }
  const submitPrescription = (event: FormEvent) => { event.preventDefault(); if (!id) return; void save(() => DashboardService.createPrescription({ patientId: id, ...prescription }), 'Prescription added to the patient record.').then(() => setPrescription({ medication: '', dosage: '', frequency: '', duration: '', instructions: '' })) }
  const submitReport = (event: FormEvent) => { event.preventDefault(); if (!id || !report.dataBase64) { setError('Choose a small report file before uploading.'); return }; void save(() => DashboardService.createMedicalReport({ patientId: id, ...report }), 'Report uploaded and stored in the profile.').then(() => setReport({ fileName: '', mimeType: '', fileSize: 0, dataBase64: '', description: '' })) }
  const submitLab = (event: FormEvent) => { event.preventDefault(); if (!id) return; void save(() => DashboardService.createLabOrder({ patientId: id, ...lab }), 'Lab order created and marked provider-ready.').then(() => setLab({ tests: '', teethCreationService: '', labName: '', labEmail: '', labPhone: '', instructions: '', copyToPatient: true, copyToClinic: true })) }
  const saveCustomerDetails = (event: FormEvent) => { event.preventDefault(); if (!id) return; void save(() => DashboardService.updatePatient(id, { firstName: customerDraft.firstName, lastName: customerDraft.lastName, email: customerDraft.email || null, phone: customerDraft.phone || null, notes: customerDraft.notes || null }), 'Customer details updated across the clinic record.') }
  const rescheduleVisit = async (visit: PatientVisit, date: string, time: string) => { await save(() => DashboardService.updateAppointment(visit.id, { appointmentDate: date, appointmentTime: time }), 'Appointment date and time updated.'); }
  const confirmCompletion = () => { if (!completionVisit) return; void save(() => DashboardService.updateAppointment(completionVisit.id, { status: 'completed', notes: completionNotes || completionVisit.summary }), 'Consultation completed and saved to the customer record.').then(() => { setCompletionVisit(null); setCompletionNotes('') }) }
  const chooseReport = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 2 * 1024 * 1024) { setError('For this workspace, report files must be 2 MB or smaller.'); return }; const reader = new FileReader(); reader.onload = () => { const result = typeof reader.result === 'string' ? reader.result : ''; setReport((current) => ({ ...current, fileName: file.name, mimeType: file.type || 'application/octet-stream', fileSize: file.size, dataBase64: result.includes(',') ? result.slice(result.indexOf(',') + 1) : result })) }; reader.readAsDataURL(file) }
  if (loading) return <div className="min-h-[calc(100vh-4rem)] px-4 py-12 text-center text-sm text-[#727783]">Loading patient profile…</div>
  if (!profile) return <div className="min-h-[calc(100vh-4rem)] px-4 py-12 text-center"><p className="text-sm text-red-700">{error || 'Patient profile not found.'}</p><button onClick={() => navigate(fromCustomerDetails ? '/dental-client/customers' : '/dental-client/patients')} className="mt-5 rounded-xl bg-[#005db6] px-4 py-3 text-xs font-bold text-white">Back to {fromCustomerDetails ? 'customers' : 'patients'}</button></div>
  const { patient } = profile
  const name = `${patient.first_name} ${patient.last_name}`
  const initials = `${patient.first_name[0] || ''}${patient.last_name[0] || ''}`
  const latestOrder = profile.lab_orders[0]
  const printableOrder = selectedPrintOrder || latestOrder
  const printLabOrder = (order: PatientLabOrder) => { setSelectedPrintOrder(order); setPrintPending(true) }
  const downloadReport = (reportId: string, fileName: string) => { if (!id) return; void DashboardService.downloadMedicalReport(id, reportId, fileName).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to download report')) }
  const downloadLabOrder = (orderId: string, orderNumber: string) => { if (!id) return; void DashboardService.downloadLabOrder(id, orderId, `${orderNumber}.pdf`).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to download lab order')) }
  return <div className="min-h-[calc(100vh-4rem)] px-4 py-6 pb-24 sm:px-6 lg:px-8">
    <div className="print:hidden">
    <button onClick={() => navigate(fromCustomerDetails ? '/dental-client/customers' : '/dental-client/patients')} className="mb-5 flex items-center gap-2 text-xs font-bold text-[#005db6] hover:underline"><ArrowLeft size={16} /> Back to {fromCustomerDetails ? 'customer details' : 'patient list'}</button>
    <header className="dental-stitch-card mb-6 overflow-hidden p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full bg-[#d6e3ff] text-xl font-bold text-[#005db6]">{initials}</div><div><p className="text-xs font-bold uppercase tracking-widest text-[#727783]">{fromCustomerDetails ? 'Customer details' : 'Patient profile'}</p><h1 className="mt-1 text-2xl font-bold text-[#151c23] sm:text-3xl">{name}</h1><p className="mt-1 text-xs text-[#727783]">Patient ID: #{patient.id.slice(0, 12)}</p></div></div><span className="flex w-fit items-center gap-2 rounded-full bg-[#dff7ed] px-3 py-2 text-xs font-bold text-[#16704d]"><CheckCircle2 size={15} /> Care record active</span></div><div className="mt-6 grid gap-4 border-t border-[#c2c6d4]/30 pt-5 sm:grid-cols-3"><Info label="Phone" value={patient.phone || 'Not provided'} /><Info label="Email" value={patient.email || 'Not provided'} /><Info label="Next appointment" value={dateLabel(patient.next_appointment)} /></div></header>
    {error && <div role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{notice && <div role="status" className="mb-5 rounded-xl bg-[#dff7ed] p-4 text-sm text-[#16704d]">{notice}</div>}
    <div role="tablist" aria-label="Patient record sections" className="dental-stitch-hide-scrollbar mb-6 flex gap-2 overflow-x-auto pb-1">{tabs.map(({ id: tabId, label, icon: Icon }) => <button key={tabId} role="tab" aria-selected={tab === tabId} onClick={() => setTab(tabId)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-xs font-bold transition ${tab === tabId ? 'bg-[#005db6] text-white shadow-md' : 'bg-white text-[#424752] hover:bg-[#e2e9f2]'}`}><Icon size={16} />{label}</button>)}</div>
    {tab === 'overview' && <div className="grid gap-5 md:grid-cols-3"><Metric label="Visits recorded" value={profile.visits.length} icon={<CalendarDays />} /><Metric label="Active prescriptions" value={profile.prescriptions.length} icon={<Pill />} /><Metric label="Lab orders" value={profile.lab_orders.length} icon={<FlaskConical />} /><section className="dental-stitch-card md:col-span-3 p-5"><h2 className="mb-4 text-lg font-bold text-[#151c23]">Care snapshot</h2><div className="grid gap-4 sm:grid-cols-2"><Snapshot icon={<Stethoscope />} title="Last visit" value={dateLabel(patient.last_visit)} /><Snapshot icon={<MapPin />} title="Contact preference" value={patient.email || patient.phone || 'Clinic follow-up'} /><Snapshot icon={<FileText />} title="Reports on file" value={`${profile.reports.length} clinical document${profile.reports.length === 1 ? '' : 's'}`} /><Snapshot icon={<ClipboardList />} title="Latest lab status" value={latestOrder ? latestOrder.dispatch_status === 'provider-ready' ? 'Provider-ready' : 'Queued' : 'No lab order yet'} /></div></section><section className="dental-stitch-card md:col-span-3 p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-[#151c23]">Customer details</h2><p className="mt-1 text-xs text-[#727783]">Updates are stored in this tenant&apos;s master record and appear in the patient list, schedule, and history.</p></div><UserRound size={20} className="text-[#005db6]" /></div><form onSubmit={saveCustomerDetails} className="grid gap-3 sm:grid-cols-2"><Field label="First name" value={customerDraft.firstName} required onChange={(value) => setCustomerDraft({ ...customerDraft, firstName: value })} /><Field label="Last name" value={customerDraft.lastName} required onChange={(value) => setCustomerDraft({ ...customerDraft, lastName: value })} /><Field label="Email" value={customerDraft.email} onChange={(value) => setCustomerDraft({ ...customerDraft, email: value })} /><Field label="Phone" value={customerDraft.phone} onChange={(value) => setCustomerDraft({ ...customerDraft, phone: value })} /><label className="block text-xs font-bold text-[#424752] sm:col-span-2">Care notes<textarea value={customerDraft.notes} onChange={(event) => setCustomerDraft({ ...customerDraft, notes: event.target.value })} className={`${inputClass} h-24 py-3`} /></label><button disabled={saving} className="w-fit rounded-xl bg-[#005db6] px-4 py-3 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save customer details'}</button></form></section></div>}
    {tab === 'visits' && <RecordList title="Visit and booking history" empty="No visits have been recorded yet." items={profile.visits.map((visit) => <VisitCard key={visit.id} visit={visit} saving={saving} onReschedule={rescheduleVisit} onComplete={(item) => { setCompletionVisit(item); setCompletionNotes(item.summary) }} />)} />}
    {tab === 'prescriptions' && <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><RecordList title="Prescription history" empty="No prescriptions have been added." items={profile.prescriptions.map((item) => <article key={item.id} className="rounded-2xl bg-[#f7f9ff] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-[#151c23]">{item.medication}</p><p className="mt-1 text-xs text-[#727783]">{item.dosage} · {item.frequency} · {item.duration}</p></div><Pill size={18} className="text-[#005db6]" /></div><p className="mt-3 text-sm text-[#424752]">{item.instructions}</p><p className="mt-2 text-[11px] text-[#727783]">{dateLabel(item.prescribed_at)} · {item.prescribed_by}</p></article>)} /><PrescriptionForm draft={prescription} setDraft={setPrescription} submit={submitPrescription} saving={saving} /></div>}
    {tab === 'reports' && <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><RecordList title="Medical reports" empty="No medical reports have been uploaded." items={profile.reports.map((item) => <article key={item.id} className="flex items-start justify-between gap-3 rounded-2xl bg-[#f7f9ff] p-4"><div className="flex min-w-0 items-start gap-3"><FileText className="mt-0.5 shrink-0 text-[#005db6]" size={20} /><div className="min-w-0"><p className="truncate text-sm font-bold text-[#151c23]">{item.file_name}</p><p className="mt-1 text-xs text-[#727783]">{formatBytes(item.file_size)} · {dateLabel(item.uploaded_at)}</p><p className="mt-2 text-sm text-[#424752]">{item.description || 'Clinical document'}</p></div><button onClick={() => downloadReport(item.id, item.file_name)} aria-label={`Download ${item.file_name}`} className="shrink-0 rounded-xl bg-white p-2 text-[#005db6] shadow-sm"><Download size={16} /></button></div></article>)} /><ReportForm report={report} setReport={setReport} chooseReport={chooseReport} submit={submitReport} saving={saving} /></div>}
    {tab === 'labs' && <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><RecordList title="Lab orders" empty="No lab orders have been created." items={profile.lab_orders.map((order) => <LabCard key={order.id} order={order} print={() => printLabOrder(order)} download={() => downloadLabOrder(order.id, order.order_number)} />)} /><LabForm draft={lab} setDraft={setLab} submit={submitLab} saving={saving} /></div>}
    {tab === 'dispatch' && <RecordList title="Traceable dispatch history" empty="No dispatch events yet." items={profile.dispatch_history.map((item) => <article key={item.id} className="flex flex-col gap-2 rounded-2xl bg-[#f7f9ff] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-[#151c23]">{item.channel === 'lab' ? 'Lab provider' : item.channel === 'patient' ? 'Patient copy' : 'Clinic copy'} · {item.recipient}</p><p className="mt-1 text-xs text-[#727783]">{dateLabel(item.created_at)} · {item.note}</p></div><Status status={item.status} /></article>)} />}
    </div><section className="hidden print:block"><h1 className="text-3xl font-bold">Dental laboratory order</h1><p className="mt-2">Patient: {name} · ID: {patient.id}</p>{printableOrder && <div className="mt-8 space-y-3 text-sm"><p><b>Order:</b> {printableOrder.order_number} · {dateLabel(printableOrder.ordered_at)}</p><p><b>Lab:</b> {printableOrder.lab_name} · {printableOrder.lab_email} · {printableOrder.lab_phone}</p><p><b>Tests:</b> {printableOrder.tests}</p><p><b>Teeth-creation service:</b> {printableOrder.teeth_creation_service}</p><p><b>Instructions:</b> {printableOrder.instructions || 'None provided'}</p></div>}</section>
    {completionVisit && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[#151c23]/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="complete-consultation-title" className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#727783]">Confirmation required</p><h2 id="complete-consultation-title" className="mt-1 text-xl font-bold text-[#151c23]">Complete consultation?</h2></div><button aria-label="Close confirmation" onClick={() => setCompletionVisit(null)} className="rounded-full p-2 text-[#727783] hover:bg-[#e2e9f2]"><X size={18} /></button></div><p className="mt-4 text-sm text-[#424752]">This will mark the {completionVisit.visit_type.toLowerCase()} for {name} as completed and save the clinical summary in the tenant record.</p><label className="mt-4 block text-xs font-bold text-[#424752]">Final consultation note<textarea value={completionNotes} onChange={(event) => setCompletionNotes(event.target.value)} className={`${inputClass} h-28 py-3`} /></label><div className="mt-5 flex justify-end gap-3"><button onClick={() => setCompletionVisit(null)} className="rounded-xl bg-[#e2e9f2] px-4 py-3 text-xs font-bold text-[#424752]">Cancel</button><button disabled={saving} onClick={confirmCompletion} className="rounded-xl bg-[#005db6] px-4 py-3 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Confirm and save'}</button></div></div></div>}
  </div>
}

function VisitCard({ visit, saving, onReschedule, onComplete }: { visit: PatientVisit; saving: boolean; onReschedule: (visit: PatientVisit, date: string, time: string) => Promise<void>; onComplete: (visit: PatientVisit) => void }) {
  const [editing, setEditing] = useState(false)
  const [date, setDate] = useState(visit.visit_date.slice(0, 10))
  const [time, setTime] = useState(visit.appointment_time?.slice(0, 5) || '09:00')
  useEffect(() => { setDate(visit.visit_date.slice(0, 10)); setTime(visit.appointment_time?.slice(0, 5) || '09:00') }, [visit.visit_date, visit.appointment_time])
  const closed = ['completed', 'cancelled', 'no_show'].includes(visit.status)
  return <article className="rounded-2xl bg-[#f7f9ff] p-4"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><p className="text-sm font-bold text-[#151c23]">{visit.visit_type}</p><p className="mt-1 flex items-center gap-1 text-xs text-[#727783]"><Clock3 size={13} /> {dateLabel(visit.visit_date)}{visit.appointment_time ? ` · ${visit.appointment_time.slice(0, 5)}` : ''} · {visit.provider}</p></div><span className={`h-fit rounded-full px-3 py-1 text-[10px] font-bold uppercase ${visit.status === 'completed' ? 'bg-[#dff7ed] text-[#16704d]' : 'bg-[#fff0d8] text-[#8a5a00]'}`}>{visit.status}</span></div><p className="mt-3 text-sm text-[#424752]">{visit.summary}</p>{visit.procedures?.length ? <p className="mt-2 text-xs text-[#727783]">Procedures: {visit.procedures.join(' · ')}</p> : null}{visit.is_appointment && !closed && <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setEditing((current) => !current)} className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-[#005db6] shadow-sm">{editing ? 'Cancel reschedule' : 'Reschedule'}</button><button disabled={saving} onClick={() => onComplete(visit)} className="rounded-xl bg-[#005db6] px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Complete consultation</button></div>}{editing && <div className="mt-3 grid gap-3 rounded-xl border border-[#c2c6d4]/40 bg-white p-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="text-xs font-bold text-[#424752]">Date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className={inputClass} /></label><label className="text-xs font-bold text-[#424752]">Time<input type="time" value={time} onChange={(event) => setTime(event.target.value)} className={inputClass} /></label><button disabled={saving || !date || !time} onClick={() => void onReschedule(visit, date, time).then(() => setEditing(false))} className="rounded-xl bg-[#16704d] px-3 py-3 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save date'}</button></div>}</article>
}
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-widest text-[#727783]">{label}</p><p className="mt-1 truncate text-sm font-semibold text-[#151c23]">{value}</p></div> }
function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="dental-stitch-card flex items-center justify-between p-5"><div><p className="text-xs font-bold uppercase tracking-widest text-[#727783]">{label}</p><p className="mt-2 text-3xl font-bold text-[#005db6]">{value}</p></div><span className="rounded-2xl bg-[#edf4fe] p-3 text-[#005db6]">{icon}</span></div> }
function Snapshot({ title, value, icon }: { title: string; value: string; icon: React.ReactNode }) { return <div className="flex items-center gap-3 rounded-2xl border border-[#c2c6d4]/30 p-4"><span className="text-[#005db6]">{icon}</span><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#727783]">{title}</p><p className="mt-1 text-sm font-semibold text-[#151c23]">{value}</p></div></div> }
function RecordList({ title, empty, items }: { title: string; empty: string; items: React.ReactNode[] }) { return <section className="dental-stitch-card p-5"><h2 className="mb-4 text-lg font-bold text-[#151c23]">{title}</h2>{items.length ? <div className="space-y-3">{items}</div> : <p className="rounded-2xl bg-[#f7f9ff] p-5 text-sm text-[#727783]">{empty}</p>}</section> }
function Status({ status }: { status: 'queued' | 'provider-ready' }) { return <span className={`w-fit rounded-full px-3 py-1 text-[10px] font-bold uppercase ${status === 'provider-ready' ? 'bg-[#dff7ed] text-[#16704d]' : 'bg-[#fff0d8] text-[#8a5a00]'}`}>{status === 'provider-ready' ? 'Provider-ready' : 'Queued'}</span> }
function PrescriptionForm({ draft, setDraft, submit, saving }: { draft: Omit<PrescriptionInput, 'patientId'>; setDraft: (draft: Omit<PrescriptionInput, 'patientId'>) => void; submit: (event: FormEvent) => void; saving: boolean }) { return <FormCard title="Add prescription" icon={<Plus size={18} />}><form onSubmit={submit} className="space-y-3"><Field label="Medication" value={draft.medication} required onChange={(value) => setDraft({ ...draft, medication: value })} /><div className="grid gap-3 sm:grid-cols-2"><Field label="Dosage" value={draft.dosage} required onChange={(value) => setDraft({ ...draft, dosage: value })} /><Field label="Frequency" value={draft.frequency} required onChange={(value) => setDraft({ ...draft, frequency: value })} /><Field label="Duration" value={draft.duration} required onChange={(value) => setDraft({ ...draft, duration: value })} /></div><label className="block text-xs font-bold text-[#424752]">Instructions<textarea required value={draft.instructions} onChange={(event) => setDraft({ ...draft, instructions: event.target.value })} className={`${inputClass} h-24 py-3`} /></label><button disabled={saving} className="w-full rounded-xl bg-[#005db6] px-4 py-3 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Add prescription'}</button></form></FormCard> }
function ReportForm({ report, setReport, chooseReport, submit, saving }: { report: { fileName: string; mimeType: string; fileSize: number; dataBase64: string; description: string }; setReport: (report: { fileName: string; mimeType: string; fileSize: number; dataBase64: string; description: string }) => void; chooseReport: (event: ChangeEvent<HTMLInputElement>) => void; submit: (event: FormEvent) => void; saving: boolean }) { return <FormCard title="Upload report" icon={<Upload size={18} />}><form onSubmit={submit} className="space-y-3"><label className="block cursor-pointer rounded-2xl border border-dashed border-[#5897f4] bg-[#edf4fe] p-5 text-center text-xs font-bold text-[#005db6]"><Upload className="mx-auto mb-2" size={22} />{report.fileName ? `${report.fileName} · ${formatBytes(report.fileSize)}` : 'Choose a file (max 2 MB)'}<input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" onChange={chooseReport} className="sr-only" /></label><label className="block text-xs font-bold text-[#424752]">Description<textarea value={report.description} onChange={(event) => setReport({ ...report, description: event.target.value })} className={`${inputClass} h-24 py-3`} placeholder="What does this report contain?" /></label><p className="text-[11px] text-[#727783]">Demo mode stores the file as base64 metadata in localStorage.</p><button disabled={saving || !report.dataBase64} className="w-full rounded-xl bg-[#005db6] px-4 py-3 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Uploading…' : 'Upload report'}</button></form></FormCard> }
function FormCard({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="dental-stitch-card h-fit p-5"><h2 className="mb-4 flex items-center gap-2 text-lg font-bold text-[#151c23]">{icon}<span>{title}</span></h2>{children}</section> }
function Field({ label, value, required, onChange }: { label: string; value: string; required?: boolean; onChange: (value: string) => void }) { return <label className="block text-xs font-bold text-[#424752]">{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} className={inputClass} /></label> }
function LabForm({ draft, setDraft, submit, saving }: { draft: Omit<LabOrderInput, 'patientId'>; setDraft: (draft: Omit<LabOrderInput, 'patientId'>) => void; submit: (event: FormEvent) => void; saving: boolean }) { return <FormCard title="Create lab order" icon={<Plus size={18} />}><form onSubmit={submit} className="space-y-3"><label className="block text-xs font-bold text-[#424752]">Tests<textarea required value={draft.tests} onChange={(event) => setDraft({ ...draft, tests: event.target.value })} className={`${inputClass} h-20 py-3`} placeholder="e.g. Bitewing radiographs, full-mouth series" /></label><Field label="Teeth-creation service" value={draft.teethCreationService} required onChange={(value) => setDraft({ ...draft, teethCreationService: value })} /><div className="grid gap-3 sm:grid-cols-2"><Field label="Lab name" value={draft.labName} required onChange={(value) => setDraft({ ...draft, labName: value })} /><Field label="Lab email" value={draft.labEmail} required onChange={(value) => setDraft({ ...draft, labEmail: value })} /><Field label="Lab phone" value={draft.labPhone} required onChange={(value) => setDraft({ ...draft, labPhone: value })} /></div><label className="block text-xs font-bold text-[#424752]">Instructions<textarea value={draft.instructions} onChange={(event) => setDraft({ ...draft, instructions: event.target.value })} className={`${inputClass} h-20 py-3`} /></label><div className="space-y-2 rounded-xl bg-[#f7f9ff] p-3 text-xs font-semibold text-[#424752]"><label className="flex items-center gap-2"><input type="checkbox" checked={draft.copyToPatient} onChange={(event) => setDraft({ ...draft, copyToPatient: event.target.checked })} /> Copy recipient: patient</label><label className="flex items-center gap-2"><input type="checkbox" checked={draft.copyToClinic} onChange={(event) => setDraft({ ...draft, copyToClinic: event.target.checked })} /> Copy recipient: clinic records</label></div><button disabled={saving} className="w-full rounded-xl bg-[#005db6] px-4 py-3 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Creating…' : 'Create lab order'}</button></form></FormCard> }
function LabCard({ order, print, download }: { order: PatientLabOrder; print: () => void; download: () => void }) { return <article className="rounded-2xl bg-[#f7f9ff] p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-sm font-bold text-[#151c23]">{order.order_number} · {order.lab_name}</p><p className="mt-1 text-xs text-[#727783]">{dateLabel(order.ordered_at)} · {order.lab_email} · {order.lab_phone}</p></div><Status status={order.dispatch_status} /></div><p className="mt-3 text-sm text-[#424752]"><b>Tests:</b> {order.tests}</p><p className="mt-1 text-sm text-[#424752]"><b>Teeth service:</b> {order.teeth_creation_service}</p><p className="mt-2 text-xs text-[#727783]">{order.dispatch_note}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={download} className="flex items-center gap-2 rounded-xl bg-[#005db6] px-3 py-2 text-xs font-bold text-white shadow-sm"><Download size={15} /> Download PDF</button><button onClick={print} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-bold text-[#005db6] shadow-sm"><FileText size={15} /> Print / save</button></div></article> }